/*
 * generated by Xtext
 */
package hu.bme.aut.gergelyszaz.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import hu.bme.aut.gergelyszaz.services.BGLGrammarAccess;

public class BGLParser extends AbstractContentAssistParser {
	
	@Inject
	private BGLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected hu.bme.aut.gergelyszaz.ui.contentassist.antlr.internal.InternalBGLParser createParser() {
		hu.bme.aut.gergelyszaz.ui.contentassist.antlr.internal.InternalBGLParser result = new hu.bme.aut.gergelyszaz.ui.contentassist.antlr.internal.InternalBGLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
					put(grammarAccess.getActionAccess().getObjectOfSelectAlternatives_3_1_0(), "rule__Action__ObjectOfSelectAlternatives_3_1_0");
					put(grammarAccess.getBooleanExpAccess().getAlternatives(), "rule__BooleanExp__Alternatives");
					put(grammarAccess.getBooleanExpAccess().getNameAlternatives_0_1_1_0(), "rule__BooleanExp__NameAlternatives_0_1_1_0");
					put(grammarAccess.getAttributeNameAccess().getAlternatives(), "rule__AttributeName__Alternatives");
					put(grammarAccess.getAttributeOrIntAccess().getAlternatives(), "rule__AttributeOrInt__Alternatives");
					put(grammarAccess.getAdditionExpAccess().getOperatorsAlternatives_1_0_0(), "rule__AdditionExp__OperatorsAlternatives_1_0_0");
					put(grammarAccess.getMultiplicationExpAccess().getAlternatives(), "rule__MultiplicationExp__Alternatives");
					put(grammarAccess.getMultiplicationExpAccess().getOperatorsAlternatives_0_1_0_0(), "rule__MultiplicationExp__OperatorsAlternatives_0_1_0_0");
					put(grammarAccess.getModelAccess().getGroup_0(), "rule__Model__Group_0__0");
					put(grammarAccess.getPlayerAccess().getGroup(), "rule__Player__Group__0");
					put(grammarAccess.getBoardAccess().getGroup(), "rule__Board__Group__0");
					put(grammarAccess.getRulesAccess().getGroup(), "rule__Rules__Group__0");
					put(grammarAccess.getTurnRulesAccess().getGroup(), "rule__TurnRules__Group__0");
					put(grammarAccess.getTokenAccess().getGroup(), "rule__Token__Group__0");
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getActionAccess().getGroup_0(), "rule__Action__Group_0__0");
					put(grammarAccess.getActionAccess().getGroup_3(), "rule__Action__Group_3__0");
					put(grammarAccess.getOrExpAccess().getGroup(), "rule__OrExp__Group__0");
					put(grammarAccess.getOrExpAccess().getGroup_1(), "rule__OrExp__Group_1__0");
					put(grammarAccess.getAndExpAccess().getGroup(), "rule__AndExp__Group__0");
					put(grammarAccess.getAndExpAccess().getGroup_1(), "rule__AndExp__Group_1__0");
					put(grammarAccess.getBooleanExpAccess().getGroup_0(), "rule__BooleanExp__Group_0__0");
					put(grammarAccess.getBooleanExpAccess().getGroup_0_1(), "rule__BooleanExp__Group_0_1__0");
					put(grammarAccess.getBooleanExpAccess().getGroup_1(), "rule__BooleanExp__Group_1__0");
					put(grammarAccess.getAttributeNameAccess().getGroup_1(), "rule__AttributeName__Group_1__0");
					put(grammarAccess.getGotoConditionAccess().getGroup(), "rule__GotoCondition__Group__0");
					put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
					put(grammarAccess.getAdditionExpAccess().getGroup(), "rule__AdditionExp__Group__0");
					put(grammarAccess.getAdditionExpAccess().getGroup_1(), "rule__AdditionExp__Group_1__0");
					put(grammarAccess.getMultiplicationExpAccess().getGroup_0(), "rule__MultiplicationExp__Group_0__0");
					put(grammarAccess.getMultiplicationExpAccess().getGroup_0_1(), "rule__MultiplicationExp__Group_0_1__0");
					put(grammarAccess.getMultiplicationExpAccess().getGroup_1(), "rule__MultiplicationExp__Group_1__0");
					put(grammarAccess.getValueAssignmentAccess().getGroup(), "rule__ValueAssignment__Group__0");
					put(grammarAccess.getSimpleAssignmentAccess().getGroup(), "rule__SimpleAssignment__Group__0");
					put(grammarAccess.getModelAccess().getNameAssignment_0_1(), "rule__Model__NameAssignment_0_1");
					put(grammarAccess.getModelAccess().getPlayerAssignment_0_2(), "rule__Model__PlayerAssignment_0_2");
					put(grammarAccess.getModelAccess().getBoardAssignment_1(), "rule__Model__BoardAssignment_1");
					put(grammarAccess.getModelAccess().getTokensAssignment_2(), "rule__Model__TokensAssignment_2");
					put(grammarAccess.getModelAccess().getRulesAssignment_3(), "rule__Model__RulesAssignment_3");
					put(grammarAccess.getPlayerAccess().getNameAssignment_0(), "rule__Player__NameAssignment_0");
					put(grammarAccess.getPlayerAccess().getPlayercountAssignment_1(), "rule__Player__PlayercountAssignment_1");
					put(grammarAccess.getPlayerAccess().getVariablesAssignment_3(), "rule__Player__VariablesAssignment_3");
					put(grammarAccess.getBoardAccess().getNameAssignment_0(), "rule__Board__NameAssignment_0");
					put(grammarAccess.getBoardAccess().getVariablesAssignment_2(), "rule__Board__VariablesAssignment_2");
					put(grammarAccess.getBoardAccess().getFieldsAssignment_3(), "rule__Board__FieldsAssignment_3");
					put(grammarAccess.getRulesAccess().getNameAssignment_0(), "rule__Rules__NameAssignment_0");
					put(grammarAccess.getRulesAccess().getTurnrulesAssignment_2(), "rule__Rules__TurnrulesAssignment_2");
					put(grammarAccess.getTurnRulesAccess().getNameAssignment_0(), "rule__TurnRules__NameAssignment_0");
					put(grammarAccess.getTurnRulesAccess().getActionsAssignment_2(), "rule__TurnRules__ActionsAssignment_2");
					put(grammarAccess.getTokenAccess().getNameAssignment_1(), "rule__Token__NameAssignment_1");
					put(grammarAccess.getTokenAccess().getVariablesAssignment_3(), "rule__Token__VariablesAssignment_3");
					put(grammarAccess.getFieldAccess().getNameAssignment_0(), "rule__Field__NameAssignment_0");
					put(grammarAccess.getFieldAccess().getXAssignment_2(), "rule__Field__XAssignment_2");
					put(grammarAccess.getFieldAccess().getYAssignment_4(), "rule__Field__YAssignment_4");
					put(grammarAccess.getFieldAccess().getZAssignment_6(), "rule__Field__ZAssignment_6");
					put(grammarAccess.getFieldAccess().getNeighboursAssignment_9(), "rule__Field__NeighboursAssignment_9");
					put(grammarAccess.getFieldAccess().getVariablesAssignment_10(), "rule__Field__VariablesAssignment_10");
					put(grammarAccess.getActionAccess().getNameAssignment_0_0(), "rule__Action__NameAssignment_0_0");
					put(grammarAccess.getActionAccess().getTokenAssignment_0_1(), "rule__Action__TokenAssignment_0_1");
					put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
					put(grammarAccess.getActionAccess().getNameAssignment_2(), "rule__Action__NameAssignment_2");
					put(grammarAccess.getActionAccess().getNameAssignment_3_0(), "rule__Action__NameAssignment_3_0");
					put(grammarAccess.getActionAccess().getObjectOfSelectAssignment_3_1(), "rule__Action__ObjectOfSelectAssignment_3_1");
					put(grammarAccess.getActionAccess().getFilterAssignment_3_3(), "rule__Action__FilterAssignment_3_3");
					put(grammarAccess.getActionAccess().getAssignmentAssignment_4(), "rule__Action__AssignmentAssignment_4");
					put(grammarAccess.getActionAccess().getGotoConditionAssignment_5(), "rule__Action__GotoConditionAssignment_5");
					put(grammarAccess.getActionAccess().getLabelAssignment_6(), "rule__Action__LabelAssignment_6");
					put(grammarAccess.getOrExpAccess().getExpressionsAssignment_0(), "rule__OrExp__ExpressionsAssignment_0");
					put(grammarAccess.getOrExpAccess().getOperatorsAssignment_1_0(), "rule__OrExp__OperatorsAssignment_1_0");
					put(grammarAccess.getOrExpAccess().getExpressionsAssignment_1_1(), "rule__OrExp__ExpressionsAssignment_1_1");
					put(grammarAccess.getAndExpAccess().getExpressionsAssignment_0(), "rule__AndExp__ExpressionsAssignment_0");
					put(grammarAccess.getAndExpAccess().getOperatorsAssignment_1_0(), "rule__AndExp__OperatorsAssignment_1_0");
					put(grammarAccess.getAndExpAccess().getExpressionsAssignment_1_1(), "rule__AndExp__ExpressionsAssignment_1_1");
					put(grammarAccess.getBooleanExpAccess().getNotAssignment_0_0(), "rule__BooleanExp__NotAssignment_0_0");
					put(grammarAccess.getBooleanExpAccess().getLeftAssignment_0_1_0(), "rule__BooleanExp__LeftAssignment_0_1_0");
					put(grammarAccess.getBooleanExpAccess().getNameAssignment_0_1_1(), "rule__BooleanExp__NameAssignment_0_1_1");
					put(grammarAccess.getBooleanExpAccess().getRightAssignment_0_1_2(), "rule__BooleanExp__RightAssignment_0_1_2");
					put(grammarAccess.getBooleanExpAccess().getNestedExpAssignment_1_1(), "rule__BooleanExp__NestedExpAssignment_1_1");
					put(grammarAccess.getAttributeNameAccess().getNameAssignment_0(), "rule__AttributeName__NameAssignment_0");
					put(grammarAccess.getAttributeNameAccess().getParentAssignment_1_0(), "rule__AttributeName__ParentAssignment_1_0");
					put(grammarAccess.getAttributeNameAccess().getChildAssignment_1_2(), "rule__AttributeName__ChildAssignment_1_2");
					put(grammarAccess.getAttributeOrIntAccess().getAttributeAssignment_0(), "rule__AttributeOrInt__AttributeAssignment_0");
					put(grammarAccess.getAttributeOrIntAccess().getValueAssignment_1(), "rule__AttributeOrInt__ValueAssignment_1");
					put(grammarAccess.getGotoConditionAccess().getConditionAssignment_1(), "rule__GotoCondition__ConditionAssignment_1");
					put(grammarAccess.getGotoConditionAccess().getNameAssignment_2(), "rule__GotoCondition__NameAssignment_2");
					put(grammarAccess.getGotoConditionAccess().getGotoAssignment_3(), "rule__GotoCondition__GotoAssignment_3");
					put(grammarAccess.getLabelAccess().getNameAssignment_1(), "rule__Label__NameAssignment_1");
					put(grammarAccess.getAdditionExpAccess().getExpressionsAssignment_0(), "rule__AdditionExp__ExpressionsAssignment_0");
					put(grammarAccess.getAdditionExpAccess().getOperatorsAssignment_1_0(), "rule__AdditionExp__OperatorsAssignment_1_0");
					put(grammarAccess.getAdditionExpAccess().getExpressionsAssignment_1_1(), "rule__AdditionExp__ExpressionsAssignment_1_1");
					put(grammarAccess.getMultiplicationExpAccess().getExpressionsAssignment_0_0(), "rule__MultiplicationExp__ExpressionsAssignment_0_0");
					put(grammarAccess.getMultiplicationExpAccess().getOperatorsAssignment_0_1_0(), "rule__MultiplicationExp__OperatorsAssignment_0_1_0");
					put(grammarAccess.getMultiplicationExpAccess().getExpressionsAssignment_0_1_1(), "rule__MultiplicationExp__ExpressionsAssignment_0_1_1");
					put(grammarAccess.getMultiplicationExpAccess().getNestedExpAssignment_1_1(), "rule__MultiplicationExp__NestedExpAssignment_1_1");
					put(grammarAccess.getValueAssignmentAccess().getNameAssignment_0(), "rule__ValueAssignment__NameAssignment_0");
					put(grammarAccess.getValueAssignmentAccess().getAdditionAssignment_2(), "rule__ValueAssignment__AdditionAssignment_2");
					put(grammarAccess.getSimpleAssignmentAccess().getNameAssignment_0(), "rule__SimpleAssignment__NameAssignment_0");
					put(grammarAccess.getSimpleAssignmentAccess().getAttributeAssignment_2(), "rule__SimpleAssignment__AttributeAssignment_2");
					put(grammarAccess.getModelAccess().getUnorderedGroup(), "rule__Model__UnorderedGroup");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			hu.bme.aut.gergelyszaz.ui.contentassist.antlr.internal.InternalBGLParser typedParser = (hu.bme.aut.gergelyszaz.ui.contentassist.antlr.internal.InternalBGLParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public BGLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BGLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
