/*
 * generated by Xtext
 */
package hu.bme.aut.gergelyszaz.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import hu.bme.aut.gergelyszaz.ui.internal.BGLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BGLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BGLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BGLActivator.getInstance().getInjector(BGLActivator.HU_BME_AUT_GERGELYSZAZ_BGL);
	}
	
}
