/*
 * generated by Xtext
 */
package hu.bme.aut.gergelyszaz.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BGLUiModule extends hu.bme.aut.gergelyszaz.ui.AbstractBGLUiModule {
	public BGLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
