/*
* generated by Xtext
*/
package hu.bme.aut.gergelyszaz.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BGLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/aut/gergelyszaz/parser/antlr/internal/InternalBGL.tokens");
	}
}
