/*
 * generated by Xtext
 */
package hu.bme.aut.gergelyszaz;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BGLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return hu.bme.aut.gergelyszaz.ui.internal.BGLActivator.getInstance().getInjector("hu.bme.aut.gergelyszaz.BGL");
	}
	
}
